mobile_service/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('mobile.urls','mobile'), namespace='mobile')),
    path('users/', include(('users.urls','users'), namespace='users')),
    path('send_email/',include(('send_email.urls','send_email'), namespace='send_email')),
]

send_email/urls.py
from django.urls import path,include
from .import views


urlpatterns=[
    path('<int:mobil_id>/<int:message_id>/', views.index, name='index'),
    path('success', views.success, name='success'),
    path('messages_new_record', views.messages_new_record, name='messages_new_record'),
    path('messages', views.messages, name='messages'),
    path('send_messages_all', views.send_messages_all, name='send_messages_all'),
    path('send_messages_all_delete/<int:message_id>/', views.send_messages_all_delete, name='send_messages_all_delete'),
    path('send_messages_all_search',views.send_messages_all_search, name='send_messages_all_search'),
    path('messages_mobil/<int:mobil_id>/', views.messages_mobil, name='messages_mobil'),
    path('messages_edit/<int:message_id>/', views.messages_edit, name='messages_edit'),
    path('messages_delete/<int:message_id>/', views.messages_delete, name='messages_delete'),
    path('messages_search', views.messages_search, name='messages_search'),
    path('settings_common', views.settings_common, name='settings_common'),
    ]

users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView
from .import views
urlpatterns=[
    path('login/', LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('individual/', views.individual, name='individual'),
    path('service_prices/', views.service_prices, name='service_prices'),
    path('service_new_record/', views.service_new_record, name='service_new_record'),
    path('service_search/', views.service_search, name='service_search'),
    path('service_edit/<int:price_id>/', views.service_edit, name = 'service_edit'),
    path('service_delete/<int:price_id>/', views.service_delete, name= 'service_delete'),
    path('details/', views.details, name= 'details'),
    path('details_all/', views.details_all, name= 'details_all'),
    path('details_all_search/', views.details_all_search, name='details_all_search'),
    path('details_new_record/', views.details_new_record, name= 'details_new_record'),
    path('details_search/', views.details_search, name= 'details_search'),
    path('details_edit/<int:detail_id>/', views.details_edit, name= 'details_edit'),
    path('details_delete/<int:detail_id>/', views.details_delete, name= 'details_delete'),
    path('details_order/', views.details_order, name= 'details_order'),
    path('details_order_new_record/', views.details_order_new_record, name= 'details_order_new_record'),
    path('details_order_search', views.details_order_search, name= 'details_order_search'),
    path('details_order_edit/<int:detail_order_id>/', views.details_order_edit, name= 'details_order_edit'),
    path('details_order_delete/<int:detail_order_id>/', views.details_order_delete, name= 'details_order_delete'),
    path('handbook/', views.handbook, name= 'handbook'),
    path('handbook_new_record/', views.handbook_new_record, name= 'handbook_new_record'),
    path('handbook_search/', views.handbook_search, name= 'handbook_search'),
    path('handbook_edit/<int:handbook_id>/', views.handbook_edit, name= 'handbook_edit'),
    path('handbook_delete/<int:handbook_id>/',views.handbook_delete, name= 'handbook_delete'),
]

send_email/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    post_message = models.CharField(max_length=20)
    text_message = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

class Settings_common(models.Model):
    """видимость другим"""
    VIS = 'Yes'
    INVIS = 'No'

    DETAIL_VISIBILITY = ((VIS, 'Yes'), (INVIS, 'No'))

    number_reg_letter = models.CharField(max_length=5, default='NUM')
    number_reg_start = models.IntegerField(default=0)
    message_send_start = models.CharField(max_length=5, default='9.00')
    message_send_finish = models.CharField(max_length=5, default='17.00')
    details_visible = models.CharField(max_length=10, choices=DETAIL_VISIBILITY)
    type_message = models.CharField(max_length=20)
    contact_number = models.CharField(max_length=20)
    free_set = models.CharField(max_length=20, choices=DETAIL_VISIBILITY)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

class Send_message(models.Model):
    send_message_start = models.CharField(max_length=5)
    send_message_finish = models.CharField(max_length=5)
    send_message_text = models.TextField()
    send_message_email = models.EmailField(max_length=254)
    send_message_number_tel = models.CharField(max_length=20)
    send_message_sticker = models.CharField(max_length=5)
    send_message_price = models.CharField(max_length=5)
    send_message_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

send_email/forms.py
from django import forms
from .models import Post, Settings_common, Send_message
from django.forms import ModelForm, Textarea

class PostForm(forms.ModelForm):
    class Meta:
        model= Post
        fields = ['post_message','text_message']
        widgets = {'text_message': Textarea(attrs={'cols': 30, 'rows': 7})}

class SettingsForm(forms.ModelForm):
    class Meta:
        model = Settings_common
        fields = ['message_send_start','message_send_finish','number_reg_letter','number_reg_start','details_visible',
                  'free_set','contact_number']
        labels = {'message_send_start':'Время начала рассылки','message_send_finish':'Время завершения рассылки',
                  'free_set':'Разрешить отправку сообщений','details_visible':'Показать каталог деталей всем',
                  'number_reg_letter':'Буквенная часть номера регистрации',
                  'number_reg_start':'Начальное цифровое значение','contact_number':'Номер для контакта'}

class Send_messageForm(forms.ModelForm):
    class Meta:
        model = Send_message
        fields = ['send_message_text']
        labels = {'send_message_text': 'текст сообщения'}
        widgets = {'send_message_text': Textarea(attrs={'cols': 30, 'rows': 5})}

send_email/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import django
from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse
from .models import Post, Settings_common, Send_message
from .forms import PostForm,SettingsForm, Send_messageForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from mobile.models import Mobil

@login_required
def index(request,mobil_id,message_id):
    message_send = Post.objects.filter(owner=request.user).get(id=message_id)
    mobil_send = Mobil.objects.filter(owner=request.user).get(id=mobil_id)
    set_1 = Settings_common.objects.filter(owner=request.user).first()
    c= Send_message(send_message_start = set_1.message_send_start,send_message_finish = set_1.message_send_finish,
                    send_message_text = message_send.text_message,send_message_email = mobil_send.email_client,
                    send_message_number_tel = mobil_send.number_tel,send_message_sticker = mobil_send.number_sticker,
                    send_message_price = mobil_send.price,owner = request.user)
    if request.method != 'POST':
        b = c
        form = Send_messageForm(instance=c)
    else:
        c.save()
        form = Send_messageForm(instance=c, data=request.POST)
        if form.is_valid():
            form.save()
        if c.send_message_email:
            if c.send_message_email != '*@gmail.com':
                send_mail('service',c.send_message_text,"Jurij", [mobil_send.email_client])
        return HttpResponseRedirect(reverse('send_email:send_messages_all'))

    context={'b':b,'mobil_id': mobil_id, 'message_id': message_id,'form':form}
    return render(request, 'send_email/index.html',context)

@login_required
def success(request):
    email = request.POST.get('email', '')
    f=open('send_email/letter.txt','r')
 #   data = """
#Hello!
#Первое сообщение из моей программы.

#    """
    data=f.read()
    send_mail('Welcome!', data, "Yasoob",
              [email], fail_silently=False)
    f.close()
    return render(request, 'send_email/success.html')

@login_required
def settings_common(request):
    set_1 = Settings_common.objects.filter(owner=request.user).first()
    if set_1:
        set_info = Settings_common.objects.filter(owner=request.user).get(id=set_1.id)
        if request.method != 'POST':
            form = SettingsForm(instance=set_info)
        else:
            form = SettingsForm(instance=set_info, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('users:individual'))
        context = {'form': form, 'set_info': set_info}
        return render(request, 'send_email/settings_common.html', context)
    else:
        if request.method != 'POST':
            form = SettingsForm()
        else:
            form = SettingsForm(request.POST)
            if form.is_valid():
                settings = form.save(commit=False)
                settings.owner = request.user
                settings.save()
                return HttpResponseRedirect(reverse('users:individual'))
        context = {'form': form}
        return render(request, 'send_email/settings_common.html', context)

@login_required
def messages_new_record(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            message_new = form.save(commit=False)
            message_new.owner = request.user
            message_new.save()
            return HttpResponseRedirect(reverse('send_email:messages'))
    context = {'form': form}
    return render(request, 'send_email/messages_new_record.html', context)

@login_required
def messages(request):
    messages = Post.objects.filter(owner=request.user).order_by('post_message','text_message')
    context = {'messages': messages}
    return render(request, 'send_email/messages.html', context)

@login_required
def messages_mobil(request,mobil_id):
    messages = Post.objects.filter(owner=request.user).order_by('post_message','text_message')
    context = {'messages': messages,'mobil_id':mobil_id}
    print('messages_mobil')
    print(mobil_id)
    return render(request, 'send_email/messages.html', context)

@login_required
def messages_edit(request,message_id):
    message = Post.objects.filter(owner=request.user).get(id=message_id)
    if request.method != 'POST':
        form = PostForm(instance=message)
    else:
        form = PostForm(instance=message, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('send_email:messages'))
    context = {'form': form, 'message': message}
    return render(request, 'send_email/messages_edit.html', context)

@login_required
def messages_delete(request, message_id):
    message = Post.objects.filter(owner=request.user).get(id=message_id)
    if request.method != 'POST':
        form = PostForm(instance=message)
    else:
        Post.objects.filter(id=message_id).delete()
        return HttpResponseRedirect(reverse('send_email:messages'))
    context = {'form': form, 'message': message}
    return render(request, 'send_email/messages_delete.html', context)

@login_required
def messages_search(request):
    query = request.GET.get('q')
    if query:
        eto_s = Post.objects.filter(owner=request.user).order_by('post_message','text_message')
        object_list = eto_s.filter(
            Q(post_message__icontains=query) | Q(text_message__icontains=query))
        context = {'object_list': object_list}
    else:
        context = {'object_list': []}
    return render(request, 'send_email/messages_search.html', context)

@login_required
def send_messages_all(request):
    send_messages_all = Send_message.objects.filter(owner=request.user).order_by('-id')
    context = {'send_messages_all': send_messages_all}
    return render(request, 'send_email/send_messages_all.html', context)

@login_required
def send_messages_all_delete(request,message_id):
    Send_message.objects.filter(id=message_id).delete()
    return HttpResponseRedirect(reverse('send_email:send_messages_all'))


@login_required
def send_messages_all_search(request):
    query = request.GET.get('q')
    if query:
        eto_s = Send_message.objects.filter(owner=request.user).order_by('-id')
        object_list = eto_s.filter(
            Q(send_message_email__icontains=query) | Q(send_message_number_tel__icontains=query))
        context = {'object_list': object_list}
    else:
        context = {'object_list': []}
    return render(request, 'send_email/send_messages_all_search.html', context)

send_email/templates/send_email/index.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2><h4>send</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'send_email:index' mobil_id message_id %}" method='post'>
    {% csrf_token %}
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
        <h4>Номер регистрации</h4>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-2 ">
        <h4>{{ b.send_message_sticker }}</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
        <h4>Номер телефона</h4>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-2 ">
        <h4>{{ b.send_message_number_tel }}</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
        <h4>Эл. почта</h4>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-2 ">
        <h4>{{ b.send_message_email }}</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
        <h4>Цена ремонта</h4>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-offset-2 ">
        <h4>{{ b.send_message_price }}</h4>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
        <h4>Сообщение</h4>
      </div>
      <div class="col-xs-12 col-sm-5 col-sm-offset-2 ">
        {% bootstrap_field form.send_message_text %}
      </div>
    </div>
    {% buttons %}
      <div class="row">
        <div class="col-sm-offset-11 ">
          <button name="submit" class="btn btn-primary">send </button>
        </div>
      </div>
    {% endbuttons %}
  </form>
{% endblock content %}

send_email/templates/send_email/messages.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2><h4>{{user.username}}</h4>
{% endblock header %}
{% block content %}
  {% if not mobil_id %}
    <div class="row">
      <div class="col-xs-12 col-sm-2">
        <a href="{% url 'send_email:send_messages_all' %}" class="btn btn-primary btn-sm">sent messages all</a>
      </div>
      <div class="col-xs-12 col-sm-offset-7">
        <form action="{% url 'send_email:messages_search' %}" method="get" autocomplete="off" >
          <input name="q" type="text" placeholder="Search...">
          <button type="submit" class="btn btn-success btn-sm">search</button>
          <a href="{% url 'send_email:messages_new_record' %}" class="btn btn-primary btn-sm">add message</a>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <h3></h3>
      </div>
    </div>
  {% endif %}
  <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr class="info">
        <th style="width:20%">Сообщение</th>
        <th>Текст</th>
        <th style="width:5%"></th>
        {% if not mobil_id %}
        <th style="width:5%"></th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for message in messages %}
        <tr>
          <td>{{message.post_message}}</td>
          <td>{{message.text_message}}</td>
        {% if not mobil_id %}
          <td><a href="{% url 'send_email:messages_edit' message.id %}" class="btn btn-warning btn-xs">edit</a></td>
        {% endif %}
        {% if not mobil_id %}
          <td><a href="{% url 'send_email:messages_delete' message.id %}" class="btn btn-danger btn-xs">delete</a></td>
        {% endif %}
        {% if mobil_id %}
          <td><a href="{% url 'send_email:index' mobil_id message.id %}" class="btn btn-warning btn-xs">send</a></td>
        {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

send_email/templates/send_email/messages_delete.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2><h4>delete</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'send_email:messages_delete' message.id %}" method='post'>
    {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.post_message %}
        </div>
        <div class ="col-xs-12 col-sm-6 col-sm-offset-1">
          {% bootstrap_field form.text_message %}
        </div>
      </div>
      {% buttons %}
        <div class="row">
          <div class="col-xs-12 col-sm-offset-10 ">
            <button name="submit" class="btn btn-primary">delete</button>
            <a href="{% url 'send_email:messages' %}" class="btn btn-danger" >
		    cancel</a>
          </div>
        </div>
      {% endbuttons %}
  </form>
{% endblock content %}

send_email/templates/send_email/messages_edit.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2><h4>edit</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'send_email:messages_edit' message.id %}" method='post'>
    {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.post_message %}
        </div>
        <div class ="col-xs-12 col-sm-6 col-sm-offset-1">
          {% bootstrap_field form.text_message %}
        </div>
      </div>
      {% buttons %}
        <div class="row">
          <div class="col-sm-offset-11">
            <button name="submit" class="btn btn-primary">save </button>
          </div>
        </div>
      {% endbuttons %}
  </form>
{% endblock content %}

send_email/templates/send_email/messages_new_record.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2><h4>new message</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'send_email:messages_new_record' %}" method='post'  class="form" autocomplete="off">
    {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.post_message %}
        </div>
        <div class ="col-xs-12 col-sm-6 col-sm-offset-1">
          {% bootstrap_field form.text_message %}
        </div>
      </div>
      {% buttons %}
        <div class="row">
          <div class="col-sm-offset-10 ">
            <button name="submit" class="btn btn-primary">add</button>
            <a href="{% url 'send_email:messages' %}" class="btn btn-danger" >
		    cancel</a>
          </div>
        </div>
      {% endbuttons %}
  </form>
{% endblock content %}

send_email/templates/send_email/messages_search.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2>
  <h4>search</h4>
{% endblock header %}
{% block content %}
  <div class="row">
    <div class="col-xs-12 col-sm-offset-11 ">
      <a href="{% url 'send_email:messages' %}" class="btn btn-danger" >
        back</a>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <h3></h3>
    </div>
  </div>
  {%if object_list %}
    <table class="table table-striped table-bordered table-condensed table-hover">
      <thead>
        <tr class="info">
          <th style="width:25%">Сообщение</th>
          <th style="width:65%">Текст</th>
          <th style="width:5%"></th>
          <th style="width:5%"></th>
        </tr>
      </thead>
      <tbody>
        {% for message in object_list %}
          <tr>
            <td>{{message.post_message}}</td>
            <td>{{message.text_message}}</td>
            <td><a href="{% url 'send_email:messages_edit' message.id %}" class="btn btn-warning btn-xs">edit</a></td>
            <td><a href="{% url 'send_email:messages_delete' message.id %}" class="btn btn-danger btn-xs">delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {%else%}
    <p><h2>The list is empty</h2></p>
  {%endif%}

{% endblock content %}

send_email/templates/send_email/send_messages_all.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2><h4>sent</h4>
{% endblock header %}
{% block content %}
  <div class="row">
      <div class="col-sm-offset-8">
        <form action="{% url 'send_email:send_messages_all_search' %}" method="get" autocomplete="off" >
          <input name="q" type="text" placeholder="Search...">
          <button type="submit" class="btn btn-success btn-sm">search</button>
        </form>
      </div>
    </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <h3></h3>
    </div>
  </div>
  <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr class="info">
        <th style="width:4%">Стикер</th>
        <th style="width:20%">Эл.почта</th>
        <th style="width:12%">N телефона</th>
        <th>Текст сообщения</th>
        <th style="width:21%">Выслано</th>
        <th style="width:4%"></th>
      </tr>
    </thead>
    <tbody>
      {% for send_message_all in send_messages_all %}
        <tr>
          <td>{{send_message_all.send_message_sticker}}</td>
          <td>{{send_message_all.send_message_email}}</td>
          <td>{{send_message_all.send_message_number_tel}}</td>
          <td>{{send_message_all.send_message_text}}</td>
          <td>{{send_message_all.send_message_date}}</td>
          <td><a href="{% url 'send_email:send_messages_all_delete' send_message_all.id %}" class="btn btn-danger btn-xs">
            delete</a></td>
        </tr>
      {% endfor %}
     </tbody>
  </table>
{% endblock content %}

send_email/templates/send_email/send_messages_all_search.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Messages</h2>
  <h4>search</h4>
{% endblock header %}
{% block content %}
  <div class="row">
    <div class="col-sm-offset-11 ">
      <a href="{% url 'send_email:send_messages_all' %}" class="btn btn-danger" >
        back</a>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <h3></h3>
    </div>
  </div>
  {%if object_list %}
    <table class="table table-striped table-bordered table-condensed table-hover">
      <thead>
        <tr class="info">
          <th style="width:4%">Стикер</th>
          <th style="width:20%">Эл.почта</th>
          <th style="width:12%">N телефона</th>
          <th>Текст сообщения</th>
          <th style="width:21%">Выслано</th>
        </tr>
      </thead>
      <tbody>
        {% for send_message_all in object_list %}
          <tr>
            <td>{{send_message_all.send_message_sticker}}</td>
            <td>{{send_message_all.send_message_email}}</td>
            <td>{{send_message_all.send_message_number_tel}}</td>
            <td>{{send_message_all.send_message_text}}</td>
            <td>{{send_message_all.send_message_date}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {%else%}
    <p><h2>The list is empty</h2></p>
  {%endif%}
{% endblock content %}

send_email/templates/send_email/settings_common.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Settings</h2><h4>{{user.username}}</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'send_email:settings_common' %}" method='post'  class="form" autocomplete="off">
    {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.free_set %}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.message_send_start %}
        </div>
        <div class ="col-xs-12 col-sm-4 col-sm-offset-1">
          {% bootstrap_field form.message_send_finish %}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.number_reg_letter %}
        </div>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.number_reg_start %}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.details_visible %}
        </div>
        <div class="col-xs-12 col-sm-4 col-sm-offset-1 ">
          {% bootstrap_field form.contact_number %}
        </div>
      </div>
      {% buttons %}
        <div class="row">
          <div class="col-sm-offset-9 ">
            <button name="submit" class="btn btn-primary">save</button>
          </div>
        </div>
      {% endbuttons %}
  </form>
{% endblock content %}

send_email/templates/send_email/success.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
<!--     <nav>
        <div class="nav-wrapper container">
          <a href="{% url 'send_email:index' %}" class="brand-logo">Django</a>
        </div>
      </nav> -->
    <div class="container login-f">
      <div class="row">
      <div class="col s12 m6 offset-m3">
        <div class="card-panel teal">
          <span class="white-text">Thank you very much! We have sent you a welcome email. Kindly read it and let us know if there is anything else we can do for you.
          <br>
          <br>
          ~Yasoob
          </span>
        </div>
      </div>
    </div>
    </div>
<!--    <footer class="page-footer">
      <div class="footer-copyright">
        <div class="container">&copy; 2015 Copyright Muhammad Yasoob
        </div>
      </div>
    </footer> -->
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript">
      function isEmail(email) {
        var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        if regex.test(email){
          document.getElementById('form').submit();
        } else{
          alert("Your email is incorrect!");
        }
      }
    </script>
  </body>
</html>