mobile/urls.py
""" URL for mobile"""
from django.urls import path,include
from .import views

urlpatterns = [
    
    path('', views.index, name='index'),
    path('telephones/', views.telephones, name='telephones'),
    path('new_record/', views.new_record, name='new_record'),
    path('edit_record/<int:mobil_id>/', views.edit_record, name='edit_record'),
    path('search/', views.search_results, name = 'search_results'),
    path('delete_record/<int:mobil_id>/',views.delete_record, name='delete_record'),
    
]

mobile_service/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('mobile.urls','mobile'), namespace='mobile')),
    path('users/', include(('users.urls','users'), namespace='users')),
    path('send_email/',include(('send_email.urls','send_email'), namespace='send_email')),
]

send_email/urls.py
from django.urls import path,include
from .import views


urlpatterns=[
    path('<int:mobil_id>/<int:message_id>/', views.index, name='index'),
    path('success', views.success, name='success'),
    path('messages_new_record', views.messages_new_record, name='messages_new_record'),
    path('messages', views.messages, name='messages'),
    path('send_messages_all', views.send_messages_all, name='send_messages_all'),
    path('send_messages_all_delete/<int:message_id>/', views.send_messages_all_delete, name='send_messages_all_delete'),
    path('send_messages_all_search',views.send_messages_all_search, name='send_messages_all_search'),
    path('messages_mobil/<int:mobil_id>/', views.messages_mobil, name='messages_mobil'),
    path('messages_edit/<int:message_id>/', views.messages_edit, name='messages_edit'),
    path('messages_delete/<int:message_id>/', views.messages_delete, name='messages_delete'),
    path('messages_search', views.messages_search, name='messages_search'),
    path('settings_common', views.settings_common, name='settings_common'),
    ]

users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView
from .import views
urlpatterns=[
    path('login/', LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('individual/', views.individual, name='individual'),
    path('service_prices/', views.service_prices, name='service_prices'),
    path('service_new_record/', views.service_new_record, name='service_new_record'),
    path('service_search/', views.service_search, name='service_search'),
    path('service_edit/<int:price_id>/', views.service_edit, name = 'service_edit'),
    path('service_delete/<int:price_id>/', views.service_delete, name= 'service_delete'),
    path('details/', views.details, name= 'details'),
    path('details_all/', views.details_all, name= 'details_all'),
    path('details_all_search/', views.details_all_search, name='details_all_search'),
    path('details_new_record/', views.details_new_record, name= 'details_new_record'),
    path('details_search/', views.details_search, name= 'details_search'),
    path('details_edit/<int:detail_id>/', views.details_edit, name= 'details_edit'),
    path('details_delete/<int:detail_id>/', views.details_delete, name= 'details_delete'),
    path('details_order/', views.details_order, name= 'details_order'),
    path('details_order_new_record/', views.details_order_new_record, name= 'details_order_new_record'),
    path('details_order_search', views.details_order_search, name= 'details_order_search'),
    path('details_order_edit/<int:detail_order_id>/', views.details_order_edit, name= 'details_order_edit'),
    path('details_order_delete/<int:detail_order_id>/', views.details_order_delete, name= 'details_order_delete'),
    path('handbook/', views.handbook, name= 'handbook'),
    path('handbook_new_record/', views.handbook_new_record, name= 'handbook_new_record'),
    path('handbook_search/', views.handbook_search, name= 'handbook_search'),
    path('handbook_edit/<int:handbook_id>/', views.handbook_edit, name= 'handbook_edit'),
    path('handbook_delete/<int:handbook_id>/',views.handbook_delete, name= 'handbook_delete'),
]

users/forms.py
from django import forms
from .models import Price_list,Details,Handbook,Details_order
from django.forms import ModelForm

class Price_listForm(forms.ModelForm):
    class Meta:
        model= Price_list
        fields = ['user_model','user_model_1','battery_type','battery_replacement','LCD_SP',
                  'LCD_orig','LCD_HQ','charging','record_1','record_2','record_3']
        labels = {'user_model':'Модель(бренд)','user_model_1':'Модель','battery_type':'Тип батареи',
                  'battery_replacement':'Замена батареи','charging':'Зарядка'}

class DetailsForm(forms.ModelForm):
    class Meta:
        model= Details
        fields = ['user_model','user_model_1','user_detail','detail_quality','detail_comment','detail_price',
                  'detail_quantity','detail_visible']
        labels = {'user_model': 'Модель(бренд)', 'user_model_1': 'Модель','user_detail':'Деталь','detail_quality':
                  'Качество','detail_comment':'Комментарии','detail_price':'Цена','detail_quantity':'Количество',
                  'detail_visible':'Показать всем'}

class Details_orderForm(forms.ModelForm):
    class Meta:
        model= Details_order
        fields = ['user_model', 'user_model_1', 'user_detail', 'detail_quality', 'detail_comment', 'detail_price',
                  'detail_quantity', 'number_tel_order']

class HandbookForm(forms.ModelForm):
    class Meta:
        model= Handbook
        fields = ['handbook_model','designation']
        labels = {'handbook_model':'Модель','designation':'Обозначение'}

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from mobile.models import Mobil
from .models import Price_list,Details,Details_order,Handbook
from send_email.models import Settings_common
from .forms import Price_listForm, DetailsForm, Details_orderForm, HandbookForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required

def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('mobile:index'))

def register(request):
    """Регистрация"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
            password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('mobile:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

@login_required
def individual(request):
    """Индивидуальные настройки"""
    return render(request, 'users/individual.html')

@login_required
def service_prices(request):
    prices = Price_list.objects.filter(owner=request.user).order_by('user_model','user_model_1')
    context = {'prices': prices}
    return render(request, 'users/service_prices.html', context)

@login_required
def service_new_record(request):
    if request.method != 'POST':
        form = Price_listForm()
    else:
        form = Price_listForm(request.POST)
        if form.is_valid():
            service_new = form.save(commit=False)
            service_new.owner = request.user
            service_new.save()
            return HttpResponseRedirect(reverse('users:service_prices'))

    context = {'form': form}
    return render(request, 'users/service_new_record.html', context)

@login_required
def service_search(request):
    query = request.GET.get('q')
    if query:
        eto_s = Price_list.objects.filter(owner=request.user)
        object_list =eto_s.filter(
            Q(user_model__icontains=query) | Q(user_model_1__icontains=query) )
        context = {'object_list': object_list}
    else:
        context = {'object_list': []}
    return render(request, 'users/service_search.html', context)

@login_required
def service_edit(request,price_id):
    price = Price_list.objects.filter(owner=request.user).get(id=price_id)
    if request.method != 'POST':
        form = Price_listForm(instance=price)
    else:
        form = Price_listForm(instance=price, data=request.POST)
        if form.is_valid():
            print("IsValid")
            form.save()
            return HttpResponseRedirect(reverse('users:service_prices'))
    context = {'form': form, 'price': price}
    return render(request, 'users/service_edit.html', context)

@login_required
def service_delete(request,price_id):
    price = Price_list.objects.filter(owner=request.user).get(id=price_id)
    if request.method != 'POST':
        form = Price_listForm(instance=price)
    else:
        Price_list.objects.filter(id=price_id).delete()
        return HttpResponseRedirect(reverse('users:service_prices'))
    context = {'form': form, 'price': price}
    return render(request, 'users/service_delete.html', context)

@login_required
def details(request):
    details = Details.objects.filter(owner=request.user).order_by('user_model','user_model_1')
    context = {'details': details}
    return render(request, 'users/details.html', context)

@login_required
def details_order(request):
    details_order = Details_order.objects.filter(owner=request.user).order_by('user_model', 'user_model_1')
    context = {'details_order': details_order}
    return render(request, 'users/details_order.html', context)

@login_required
def details_all(request):
    details_all = Details.objects.order_by('user_model', 'user_model_1')
    set_2 = []
    set_3 = {}
    all_owners = Settings_common.objects.order_by('owner')
    for all_owner in all_owners:
        if all_owner.details_visible == 'Yes':
            set_2.append(all_owner.owner_id)
            set_3[all_owner.owner_id]= all_owner.contact_number
    context = {'details_all': details_all,'set_2':set_2,'set_3': set_3}
    return render(request, 'users/details_all.html', context)

@login_required
def details_new_record(request):
    if request.method != 'POST':
        form = DetailsForm()
    else:
        form = DetailsForm(request.POST)
        if form.is_valid():
            detail_new = form.save(commit=False)
            detail_new.owner = request.user
            detail_new.save()
            return HttpResponseRedirect(reverse('users:details'))
    context = {'form': form}
    return render(request, 'users/details_new_record.html', context)

@login_required
def details_order_new_record(request):
    if request.method != 'POST':
        form = Details_orderForm()
    else:
        form = Details_orderForm(request.POST)
        if form.is_valid():
            detail_order_new = form.save(commit=False)
            detail_order_new.owner = request.user
            detail_order_new.save()
            return HttpResponseRedirect(reverse('users:details_order'))
    context = {'form': form}
    return render(request, 'users/details_order_new_record.html', context)


@login_required
def details_search(request):
    query = request.GET.get('q')
    if query:
        eto_s = Details.objects.filter(owner=request.user).order_by('user_model','user_model_1')
        object_list = eto_s.filter(
            Q(user_model__icontains=query) | Q(user_model_1__icontains=query) | Q(detail_visible__icontains=query))
        context = {'object_list': object_list}
    else:
        context = {'object_list': []}
    return render(request, 'users/details_search.html', context)

@login_required
def details_all_search(request):
    query = request.GET.get('q')
    if query:
        set_2 = []
        set_3 = {}
        all_owners = Settings_common.objects.order_by('owner')
        for all_owner in all_owners:
            if all_owner.details_visible == 'Yes':
                set_2.append(all_owner.owner_id)
                set_3[all_owner.owner_id] = all_owner.contact_number
        details_search = Details.objects.filter(owner_id__in= set_2).filter(detail_visible__iexact='Yes').order_by\
            ('user_model', 'user_model_1')
        object_list = details_search.filter(
            Q(user_model__icontains=query) | Q(user_model_1__icontains=query))
        context = {'object_list': object_list, 'set_3': set_3}
    else:
        context = {'object_list': []}
    return render(request, 'users/details_all_search.html', context)

@login_required
def details_order_search(request):
    query = request.GET.get('q')
    if query:
        eto_s = Details_order.objects.filter(owner=request.user).order_by('user_model','user_model_1')
        object_list = eto_s.filter(
            Q(user_model__icontains=query) | Q(user_model_1__icontains=query) | Q(number_tel_order__exact=query))
        context = {'object_list': object_list}
    else:
        context = {'object_list': []}
    return render(request, 'users/details_order_search.html', context)


@login_required
def details_edit(request,detail_id):
    detail = Details.objects.filter(owner=request.user).get(id=detail_id)
    if request.method != 'POST':
        form = DetailsForm(instance=detail)
    else:
        form = DetailsForm(instance=detail, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:details'))
    context = {'form': form, 'detail': detail}
    return render(request, 'users/details_edit.html', context)

@login_required
def details_order_edit(request,detail_order_id):
    detail_order = Details_order.objects.filter(owner=request.user).get(id=detail_order_id)
    if request.method != 'POST':
        form = Details_orderForm(instance=detail_order)
    else:
        form = Details_orderForm(instance=detail_order, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:details_order'))
    context = {'form': form, 'detail_order': detail_order}
    return render(request, 'users/details_order_edit.html', context)

@login_required
def details_delete(request,detail_id):
    detail = Details.objects.filter(owner=request.user).get(id=detail_id)
    if request.method != 'POST':
        form = DetailsForm(instance=detail)
    else:
        Details.objects.filter(id=detail_id).delete()
        return HttpResponseRedirect(reverse('users:details'))
    context = {'form': form, 'detail': detail}
    return render(request, 'users/details_delete.html', context)

@login_required
def details_order_delete(request,detail_order_id):
    detail_order = Details_order.objects.filter(owner=request.user).get(id=detail_order_id)
    if request.method != 'POST':
        form = Details_orderForm(instance=detail_order)
    else:
        Details_order.objects.filter(id=detail_order_id).delete()
        return HttpResponseRedirect(reverse('users:details_order'))
    context = {'form': form, 'detail_order': detail_order}
    return render(request, 'users/details_order_delete.html', context)

@login_required
def handbook(request):
    handbooks = Handbook.objects.filter(owner=request.user).order_by('handbook_model')
    context = {'handbooks': handbooks}
    return render(request, 'users/handbook.html',context)

@login_required
def handbook_new_record(request):
    if request.method != 'POST':
        form = HandbookForm()
    else:
        form = HandbookForm(request.POST)
        if form.is_valid():

users/templates/users/details.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Details</h2><h4>{{user.username}}</h4>
{% endblock header %}
{% block content %}
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        <a href="{% url 'users:details_all' %}" class="btn btn-primary btn-sm">all details</a>
        <a href="{% url 'users:details_order' %}" class="btn btn-primary btn-sm">orders</a>
      </div>
      <div class="col-xs-12 col-sm-offset-7">
        <form action="{% url 'users:details_search' %}" method="get" autocomplete="off" >
          <input name="q" type="text" placeholder="Search...">
          <button type="submit" class="btn btn-success btn-sm">search</button>
          <a href="{% url 'users:details_new_record' %}" class="btn btn-primary btn-sm">add record</a>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-8">
        <h3></h3>
      </div>
    </div>
   <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr class="info">
        <th colspan="2">Модель телефона</th>
        <th style="width:16%">Деталь</th>
        <th style="width:8%">Качество</th>
        <th style="width:24%">Комментарий</th>
        <th style="width:7%">Цена</th>
        <th style="width:7%">Кол-во</th>
        <th style="width:3%">Вид</th>
        <th style="width:5%"></th>
        <th style="width:5%"></th>
      </tr>
    </thead>
    <tbody>
      {% for detail in details %}
        <tr>
          <td>{{detail.user_model}}</td>
          <td>{{detail.user_model_1}}</td>
          <td>{{detail.user_detail}}</td>
          <td>{{detail.detail_quality}}</td>
          <td>{{detail.detail_comment}}</td>
          <td>{{detail.detail_price}}</td>
          <td>{{detail.detail_quantity}}</td>
          <td>{{detail.detail_visible}}</td>
          <td><a href="{% url 'users:details_edit' detail.id %}" class="btn btn-warning btn-xs">edit</a></td>
          <td><a href="{% url 'users:details_delete' detail.id %}" class="btn btn-danger btn-xs">delete</a></td>
        </tr>
      {% endfor %}
     </tbody>
  </table>
{% endblock content %}

users/templates/users/handbook.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Handbook</h2><h4>{{user.username}}</h4>
{% endblock header %}
{% block content %}
  <div class="row">
    <div class="col-xs-12 col-sm-offset-7">
      <form action="{% url 'users:handbook_search' %}" method="get" autocomplete="off" >
        <input name="q" type="text" placeholder="Search...">
        <button type="submit" class="btn btn-success btn-sm">search</button>
        <a href="{% url 'users:handbook_new_record' %}" class="btn btn-primary btn-sm">add record</a>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <h3></h3>
    </div>
  </div>
    <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr class="info">
        <th>Модель телефона</th>
        <th>Маркировка</th>
        <th style="width:5%"></th>
        <th style="width:5%"></th>
      </tr>
    </thead>
    <tbody>
      {% for handbook in handbooks %}
        <tr>
          <td>{{handbook.handbook_model}}</td>
          <td>{{handbook.designation}}</td>
          <td><a href="{% url 'users:handbook_edit' handbook.id %}" class="btn btn-warning btn-xs">edit</a></td>
          <td><a href="{% url 'users:handbook_delete' handbook.id %}" class="btn btn-danger btn-xs">delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

users/templates/users/handbook_delete.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Handbook</h2>
  <h4>delete</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'users:handbook_delete' handbook.id %}" method='post'>
    {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          {% bootstrap_field form.handbook_model %}
        </div>
        <div class ="col-xs-12 col-sm-4">
          {% bootstrap_field form.designation %}
        </div>
      </div>
    {% buttons %}
      <div class="row">
        <div class="col-sm-offset-10 ">
          <button name="submit" class="btn btn-primary">delete</button>
          <a href="{% url 'users:handbook' %}" class="btn btn-danger" >
		    cancel</a>
        </div>
      </div>
    {% endbuttons %}
  </form>
{% endblock content %}

users/templates/users/handbook_edit.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Handbook</h2><h4>edit</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'users:handbook_edit' handbook.id %}" method='post'>
    {% csrf_token %}
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          {% bootstrap_field form.handbook_model %}
        </div>
        <div class ="col-xs-12 col-sm-4">
          {% bootstrap_field form.designation %}
        </div>
      </div>
    {% buttons %}
      <div class="row">
        <div class="col-sm-offset-10 ">
          <button name="submit" class="btn btn-primary">save</button>
          <a href="{% url 'users:handbook' %}" class="btn btn-danger" >
		    cancel</a>
        </div>
      </div>
    {% endbuttons %}
  </form>
{% endblock content %}

users/templates/users/handbook_new_record.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Handbook</h2><h4>new record</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'users:handbook_new_record' %}" method='post'  class="form" autocomplete="off">
    {% csrf_token %}
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        {% bootstrap_field form.handbook_model %}
      </div>
      <div class ="col-xs-12 col-sm-4">
        {% bootstrap_field form.designation %}
      </div>
    </div>
    {% buttons %}
      <div class="row">
        <div class="col-sm-offset-10 ">
          <button name="submit" class="btn btn-primary">add</button>
          <a href="{% url 'users:handbook' %}" class="btn btn-danger" >
		    cancel</a>
        </div>
      </div>
    {% endbuttons %}
  </form>
{% endblock content %}

users/templates/users/individual.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Individual</h2><h4>{{user.username}}</h4>
{% endblock header %}
{% block content %}
  <div class="row">
    <div class="col-xs-12 col-sm-offset-1">
      <a href="{% url 'users:service_prices' %}"><h3>Service prices</h3></a>
    </div>
    <div class="col-xs-12 col-sm-offset-2">
      <h4>- Раздел  содержит информацию о ценах на услуги.</h4>
      <h4>- Поиск осуществляется по модели телефона. </h4>
    </div>
    <div class="col-xs-12 col-sm-offset-1">
      <a href="{% url 'mobile:telephones' %}"><h3>Telephones</h3></a>
    </div>
    <div class="col-xs-12 col-sm-offset-2">
      <h4>- Основная информация хранится в базе данных раздела.</h4>
      <h4>- Регистр - номер регистрации в базе данных. Он состоит из букв и цифровой части.</h4>
      <h4>&nbsp;&nbsp;В разделе Settings обе части необходимо указать перед самым первым началом </h4>
      <h4>&nbsp;&nbsp;пользования программой. Цифровая часть регистрации увеличивается автоматически</h4>
      <h4>&nbsp;&nbsp;на 1 (от максимального значения в памяти) при каждой новой записи.</h4>
      <h4>&nbsp;&nbsp;По превышении 99999 - обнуляется.</h4>
      <h4>- Стикер - номер регистрации сервиса.</h4>
      <h4>&nbsp;&nbsp;Указывается при добавлении/редактировании записи в произвольном порядке.</h4>
      <h4>- Аналогично вводится остальная информация.</h4>
      <h4>- Заполнение всех окон формы является обязательным.</h4>
      <h4>- При наличии информации о номере телефона или адресе электронной почты</h4>
      <h4>&nbsp;&nbsp;клиента (а также в Settings "Разрешить отправку сообщений" - в положении "Yes")</h4>
      <h4>&nbsp;&nbsp;в режиме edit активируется ссылка Send message.</h4>
      <h4>&nbsp;&nbsp;Дальнейшие действия по этой ссылке описаны в разделе Messages.</h4>
      <h4>- Поиск осуществляется по модели телефона, номеру регистрации, номеру стикера,</h4>
      <h4>&nbsp;&nbsp;неисправности, статусу, комментариям,IMEI, номеру телефона клиента.</h4>
    </div>
    <div class="col-xs-12 col-sm-offset-1">
      <a href="{% url 'users:details' %}"><h3>Details</h3></a>
    </div>
    <div class="col-xs-12 col-sm-offset-2">
      <h4>- Содержится информация о деталях, имеющихся в наличии в данном сервисе.</h4>
      <h4>- При вводе/редактировании запись содержит позицию "Показать всем" - показать всем </h4>
      <h4>&nbsp;&nbsp;пользователям сайта ( в таблице отображается в столбце "Вид").</h4>
      <h4>- Общий запрет/разрешение "Показать каталог деталей всем" устанавливается в Settings.</h4>
      <h4>- Поиск осуществляется по модели телефона.</h4>
      <h4>- Orders - каталог заказанных деталей данного сервиса.</h4>
      <h4>- All details - свои детали и детали участников сайта, разрешённые ими к просмотру. </h4>
    </div>
    <div class="col-xs-12 col-sm-offset-1">
      <a href="{% url 'users:handbook' %}"><h3>Handbook</h3></a>
    </div>
    <div class="col-xs-12 col-sm-offset-2">
      <h4>- Соответствие модели телефона надписи на нём.</h4>
      <h4>- Поиск - по каждому параметру.</h4>
    </div>
    <div class="col-xs-12 col-sm-offset-1">
      <a href="{% url 'send_email:messages' %}"><h3>Messages</h3></a>
    </div>
    <div class="col-xs-12 col-sm-offset-2">
      <h4>- Содержит таблицу шаблонов сообщений. </h4>
      <h4>- При прохождении TELEPHONES --> edit --> Send message из таблицы MESSAGES </h4>
      <h4>&nbsp;&nbsp;используеся наиболее подходящий шаблон, который затем редактируется и отсылается.</h4>
      <h4>- Sent messages all - переход к таблице высланных сообщений.</h4>
      <h4>- В данной версии программы используются только e-mail сообщения.</h4>
      <h4>- Поиск - по совпадению слов с текстом сообщений.</h4>
    </div>
    <div class="col-xs-12 col-sm-offset-1">
      <a href="{% url 'send_email:settings_common' %}"><h3>Settings</h3></a>
    </div>
    <div class="col-xs-12 col-sm-offset-2">
      <h4>- Некоторые общие настройки.</h4>
    </div>
  </div>
{% endblock content %}

users/templates/users/login.html
{% extends "mobile/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
  <form method="post" action="{% url 'users:login' %}" class="form" autocomplete="off">
  {% csrf_token %}
  <div class="row">
    <div class="col-sm-4">
      {% bootstrap_field form.username %}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
      {% bootstrap_field form.password %}
    </div>
  </div>
    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'users:individual' %}" />
  </form>
{% endblock content %}

users/templates/users/service_search.html
{% extends "mobile/base_1.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Service prices</h2>
  <h4>search</h4>
{% endblock header %}
{% block content %}
  {%if object_list %}
    <table class="table table-striped table-bordered table-condensed table-hover">
      <thead>
        <tr class="info">
          <th colspan="2">Модель телефона</th>
          <th style="width:8%">Тип батареи</th>
          <th style="width:8%">Замена батареи</th>
          <th style="width:8%">LCD SP</th>
          <th style="width:8%">LCD ориг</th>
          <th style="width:8%">LCD HQ</th>
          <th style="width:8%">Зарядка</th>
          <th style="width:8%">record_1</th>
          <th style="width:8%">record_2</th>
          <th style="width:8%">record_3</th>
          <th style="width:5%"></th>
          <th style="width:5%"></th>
        </tr>
      </thead>
      <tbody>
        {% for price in object_list %}
          <tr>
            <td>{{price.user_model}}</td>
            <td>{{price.user_model_1}}</td>
            <td>{{price.battery_type}}</td>
            <td>{{price.battery_replacement}}</td>
            <td>{{price.LCD_SP}}</td>
            <td>{{price.LCD_orig}}</td>
            <td>{{price.LCD_HQ}}</td>
            <td>{{price.charging}}</td>
            <td>{{price.record_1}}</td>
            <td>{{price.record_2}}</td>
            <td>{{price.record_3}}</td>
            <td><a href="{% url 'users:service_edit' price.id %}" class="btn btn-warning btn-xs">edit</a></td>
            <td><a href="{% url 'users:service_delete' price.id %}" class="btn btn-danger btn-xs">delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {%else%}
    <p><h2>The list is empty</h2></p>
  {%endif%}
    <div class="row">
      <div class="col-xs-12 col-sm-offset-11 ">
        <a href="{% url 'users:service_prices' %}" class="btn btn-danger" >
          cancel</a>
      </div>
    </div>
{% endblock content %}