mobile/urls.py
""" URL for mobile"""
from django.urls import path,include
from .import views

urlpatterns = [
    
    path('', views.index, name='index'),
    path('telephones/', views.telephones, name='telephones'),
    path('new_record/', views.new_record, name='new_record'),
    path('edit_record/<int:mobil_id>/', views.edit_record, name='edit_record'),
    path('search/', views.search_results, name = 'search_results'),
    path('delete_record/<int:mobil_id>/',views.delete_record, name='delete_record'),
    
]

mobile_service/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('mobile.urls','mobile'), namespace='mobile')),
    path('users/', include(('users.urls','users'), namespace='users')),
    path('send_email/',include(('send_email.urls','send_email'), namespace='send_email')),
]

send_email/urls.py
from django.urls import path,include
from .import views


urlpatterns=[
    path('<int:mobil_id>/<int:message_id>/', views.index, name='index'),
    path('success', views.success, name='success'),
    path('messages_new_record', views.messages_new_record, name='messages_new_record'),
    path('messages', views.messages, name='messages'),
    path('send_messages_all', views.send_messages_all, name='send_messages_all'),
    path('send_messages_all_delete/<int:message_id>/', views.send_messages_all_delete, name='send_messages_all_delete'),
    path('send_messages_all_search',views.send_messages_all_search, name='send_messages_all_search'),
    path('messages_mobil/<int:mobil_id>/', views.messages_mobil, name='messages_mobil'),
    path('messages_edit/<int:message_id>/', views.messages_edit, name='messages_edit'),
    path('messages_delete/<int:message_id>/', views.messages_delete, name='messages_delete'),
    path('messages_search', views.messages_search, name='messages_search'),
    path('settings_common', views.settings_common, name='settings_common'),
    ]

users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView
from .import views
urlpatterns=[
    path('login/', LoginView.as_view(template_name='users/login.html'),
        name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('individual/', views.individual, name='individual'),
    path('service_prices/', views.service_prices, name='service_prices'),
    path('service_new_record/', views.service_new_record, name='service_new_record'),
    path('service_search/', views.service_search, name='service_search'),
    path('service_edit/<int:price_id>/', views.service_edit, name = 'service_edit'),
    path('service_delete/<int:price_id>/', views.service_delete, name= 'service_delete'),
    path('details/', views.details, name= 'details'),
    path('details_all/', views.details_all, name= 'details_all'),
    path('details_all_search/', views.details_all_search, name='details_all_search'),
    path('details_new_record/', views.details_new_record, name= 'details_new_record'),
    path('details_search/', views.details_search, name= 'details_search'),
    path('details_edit/<int:detail_id>/', views.details_edit, name= 'details_edit'),
    path('details_delete/<int:detail_id>/', views.details_delete, name= 'details_delete'),
    path('details_order/', views.details_order, name= 'details_order'),
    path('details_order_new_record/', views.details_order_new_record, name= 'details_order_new_record'),
    path('details_order_search', views.details_order_search, name= 'details_order_search'),
    path('details_order_edit/<int:detail_order_id>/', views.details_order_edit, name= 'details_order_edit'),
    path('details_order_delete/<int:detail_order_id>/', views.details_order_delete, name= 'details_order_delete'),
    path('handbook/', views.handbook, name= 'handbook'),
    path('handbook_new_record/', views.handbook_new_record, name= 'handbook_new_record'),
    path('handbook_search/', views.handbook_search, name= 'handbook_search'),
    path('handbook_edit/<int:handbook_id>/', views.handbook_edit, name= 'handbook_edit'),
    path('handbook_delete/<int:handbook_id>/',views.handbook_delete, name= 'handbook_delete'),
]

mobile/models.py
from django.db import models
from django.contrib.auth.models import User
#from multiselectfield import MultiSelectField

class Mobil(models.Model):
    """информация о телефонах"""

    """модели"""
    SAM = 'Samsung'
    ALK = 'Alkatel'
    ASE = 'Aser'
    AMI = 'Amigo'
    AMO = 'Amoi'
    APL = 'IPhone'
    ASU = 'Asus'
    BBR = 'BlackBerry'
    BVI = 'BlackView'
    BLU = 'BLU'
    BQ = 'BQ'
    CAT = 'CAT'
    CAP = 'Caterpillar'
    COO = 'Coolpad'
    CUB = 'Cubot'
    DOO = 'Doogee'
    DOR = 'Doro'
    EST = 'Estar'
    ELE = 'Elephone'
    GIG = 'Gigabyte'
    GET = 'Getnord'
    GOO = 'Google'
    HTC = 'HTC'
    HP = 'HP'
    HOM = 'HomTom'
    KAZ = 'Kazam'
    MYP = 'MyPhone'
    NOU = 'Nous'
    ONE = 'OnePlus'
    OUK = 'Oukitel'
    PRE = 'Prestigio'
    ZTE = 'ZTE'
    ZOP = 'Zopo'
    HUA = 'Huawei'
    LEN = 'Lenovo'
    SON = 'Sony'
    LG = 'LG'
    MEI = 'Meizu'
    XIA = 'Xiaomi'
    MIR = 'Microsoft'
    NOK = 'Nokia'
    OTH = '------->'

    """неисправности"""
    LCD = 'lcd'
    DIN = 'speaker'
    BUZ = 'buzzer'
    KOD = 'kod'
    AKK = 'akkaunt'
    MIC = 'microphone'
    WIF = 'wi_fi'
    PRO = 'programm'
    HEN = 'hands_free'
    N_C = 'not_charging'
    WET = 'wet'
    SIM = 'sim'
    NTO1 = 'не вкл'
    NTO2 = 'не вкл, мокрый'
    NTO3 = 'не вкл,падал'
    LCT = 'lcd/touch'
    TOU = 'touch'
    LANG = 'languige'
    UNLO = 'unlock'
    FLEX = 'flex'
    CASE = 'case'


    """состояние"""
    NVD = 'no visible defects'
    DLT = 'damaded_LCD/Touch'
    DCS = 'damaded_case'
    DBC = "damaded_back_cover"

    """статус"""
    REP = 'Ремонт'
    REP_COM = 'Рем.завершен'
    TEL_TA = 'Забран'
    BRAND = ((APL,'IPhone'),(SAM,'Samsung'),(HUA,'Huawei'),(MEI,'Meizu'),(XIA,'Xiaomi'),(NOK,'Nokia'),(MIR,'Microsoft'),
        (PRE,'Prestigio'),(SON,'Sony'),(ALK,'Alcatel'),(ASU,'Asus'),(ASE,'Aser'),(AMI,'Amigo'),(AMO,'Amoi'),
        (BVI,'BlackView'),(BLU,'BLU'),(BQ,'BQ'),(BBR,'BlackBerry'),(CAT,'CAT'),(CAP,'Caterpillar'),(COO,'Coolpad'),
        (CUB,'Cubot'),(DOO,'Doogee'),(DOR,'Doro'),(ELE,'Elephone'),(EST,'Estar'),(GIG,'Gigabyte'),(GET,'Getnord'),
        (GOO,'Google'),(HTC,'HTC'),(HOM,'HomTom'),(HP,'HP'),(KAZ,'Kazam'),(LEN,'Lenovo'),(LG,'Lg'),(MYP,'MyPhone'),
        (NOU,'Nous'),(ONE,'OnePlus'),(OUK,'Oukitel'),(ZOP,'Zopo'),(ZTE,'ZTE'),(OTH,'------->'))
    DEFECT = ((PRO,'Programm'),(LANG,'Язык'),(UNLO,'Отвязка'),(KOD,'Код'),(AKK,'Аккаунт'),(LCT,'LCD/Touch'),(LCD,'LCD'),
        (TOU,'Touch'),(NTO1,'Не вкл'),(NTO2,'Не вкл, Мокрый'),(NTO3,'Не вкл, Падал'),(N_C,'Не заряж'),(DIN,'Динамик'),
        (BUZ,'Зуммер'),(MIC,'Микрофон'),(HEN,'Hands_Free'),(WIF,'Wi-Fi'),(WET,'Мокрый'),(SIM,'Sim'),(FLEX,'Шлейф'),
        (CASE,'Корпус'),(OTH,'------->'))
    STATUS = ((REP,'ремонт'),(REP_COM,'ремонт_завершён'),(TEL_TA,'забран'))
    STATE = ((NVD,'Нет видимых дефектов'),(DLT,'Повреждён экран/тоучскрин'),(DCS,'Повреждён корпус'),
        (DBC,'Повреждена задняя крышка'))
    
    
    number_reg = models.IntegerField(default=0)
    complex_number_reg = models.CharField(max_length=10)
    number_sticker = models.CharField(max_length=5)
    model_tel = models.CharField(max_length=20,choices=BRAND)
    model_1_tel = models.CharField(max_length=20)
    kod_tel = models.CharField(max_length=20,default='*')
    price = models.CharField(max_length=5)
    imei = models.CharField(max_length=20)
    number_tel = models.CharField(max_length=20, default='+370')
    date_added = models.DateTimeField(auto_now_add=True)
    date_end = models.CharField(max_length=12,default='*')
    date_take_away = models.CharField(max_length=12,default='*')
    state = models.CharField(max_length=20,choices=STATE)
    status = models.CharField(max_length=20,choices=STATUS,default=REP)
#    defect_tel = MultiSelectField(choices=DEFECT)
    defect = models.CharField(max_length=30,default='*')
    defect_tel = models.CharField(max_length=20,choices=DEFECT)
    defect_1_tel = models.CharField(max_length=20,choices=DEFECT,default='*')
    comment = models.CharField(max_length=200,default='*')
    email_client = models.EmailField(max_length=254, default='*@gmail.com')
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def _str_(self):
        return self.number_reg

mobile/forms.py
from django import forms
from .models import Mobil
from django.forms import ModelForm,MultipleChoiceField


class MobilForm(forms.ModelForm):
    class Meta:
        model = Mobil
        fields=['number_sticker','model_tel','model_1_tel','imei','number_tel','state','price','defect',
            'defect_tel','kod_tel','comment','email_client']
        labels = {'number_sticker':'Стикер','model_tel':'Модель(бренд)','model_1_tel':'Модель','imei':'IMEI',
            'number_tel':'Номер телефона','state':'Состояние','price':'Цена','defect':'Дефект(дополнение)',
            'defect_tel':'Дефект','kod_tel':'Код телефона','comment':'Комментарии','email_client':'EMAIL' }
        help_texts = {'model_tel':'если нет в списке, укажите ------->',
            'model_1_tel':('а здесь введите полное наименование'),
            'defect_tel':'если нет в списке, укажите ------->','defect':'а здесь введите неисправность'}

class EditForm(forms.ModelForm):
    class Meta:
        model = Mobil
        fields=['number_sticker','model_tel','model_1_tel','imei','number_tel','state','price',
            'defect_tel','defect','kod_tel','status','date_end','date_take_away','number_reg','comment','email_client']
        labels = {'number_sticker':'Стикер','model_tel':'Модель(бренд)','model_1_tel':'Модель','imei':'IMEI',
            'number_tel':'Номер телефона','state':'Состояние','price':'Цена','defect':'Дефект(дополнение)',
            'defect_tel':'Дефект','kod_tel':'Код телефона','comment':'Комментарии','number_reg':'Регистр.номер',
            'status':'Статус','date_end':'Дата завершения ремонта','date_take_away':'Забран(дата)',
            'email_client':'EMAIL'}

mobile/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404
from .models import Mobil
from send_email.models import Settings_common
from .forms import MobilForm,EditForm
from django.views.generic import ListView
from django.db.models import Q
from django.db.models import Max

def index(request):
    """home page"""
    return render(request, 'mobile/index.html')

@login_required
def telephones(request):
    mobils = Mobil.objects.filter(owner=request.user).order_by('-number_reg')
    context = {'mobils': mobils}
    return render(request, 'mobile/telephones.html', context)

@login_required
def new_record(request):
    if request.method != 'POST':
        form = MobilForm()
    else:
        form = MobilForm(request.POST)
        if form.is_valid():
            nform=form.save(commit=False)
            own_list = Mobil.objects.filter(owner=request.user)
            set_1 = Settings_common.objects.filter(owner=request.user).first()
            max_num = own_list.aggregate(Max('number_reg'))
            if not own_list:
                max_num['number_reg__max']=set_1.number_reg_start-1
            next_number_reg = max_num['number_reg__max']+1
            if next_number_reg > 99999:
                next_number_reg = 0
            nform.number_reg = str(next_number_reg)
            alen_1 = set_1.number_reg_letter + " "
            alen = len(nform.number_reg)
            while alen < 5:
                alen_1 += '0'
                alen +=1
            nform.complex_number_reg = alen_1 + str(next_number_reg)
            nform.owner = request.user
            nform.save()
            return HttpResponseRedirect(reverse('mobile:telephones'))
    context = {'form': form}
    return render(request, 'mobile/new_record.html', context)

@login_required
def edit_record(request,mobil_id):
    mobil=Mobil.objects.filter(owner=request.user).get(id=mobil_id)
    set_1 = Settings_common.objects.filter(owner=request.user).first()
    if request.method != 'POST':
        form = EditForm(instance=mobil)
    else:
        form = EditForm(instance=mobil, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mobile:telephones'))
    context = {'form': form,'mobil':mobil,'set_1':set_1}
    return render(request, 'mobile/edit_record.html', context)

@login_required
def delete_record(request,mobil_id):
    mobil=Mobil.objects.get(id=mobil_id)
    if request.method !='POST':
        form = EditForm(instance=mobil)
    else:
        Mobil.objects.filter(id=mobil_id).delete()
        return HttpResponseRedirect(reverse('mobile:telephones'))
    context = {'form': form, 'mobil': mobil}
    return render( request, 'mobile/delete_record.html',context)

@login_required
def search_results(request):
    query = request.GET.get('q')
    if query:
        eto = Mobil.objects.filter(owner=request.user)
        object_list =eto.filter(
            Q(model_tel__icontains=query) | Q(imei__exact=query) | Q(number_tel__exact=query) |
            Q(model_1_tel__icontains=query) | Q(number_sticker__exact=query) | Q(comment__icontains=query)
            | Q(number_reg__icontains=query) | Q(defect_tel__icontains=query) | Q(defect__icontains=query)
            | Q(status__icontains=query)
                ).order_by('-number_reg')
        context = {'object_list': object_list}
    else:
        context = {'object_list': []}
    return render(request, 'mobile/search_results.html', context)


            

    

        
        
    

mobile/templates/mobile/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MobileService</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Статическая навигационная панель -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'mobile:index' %}">
              MobileService</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
<!--          <ul class="nav navbar-nav">
            <li><a href="{% url 'mobile:index' %}"> MobileService</a></li>
          </ul>   -->
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
              <li><a href="{% url 'send_email:settings_common' %}">settings</a></li>
              <li><a href="{% url 'users:individual' %}">individual</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!-- /container -->
  </body>
</html>

mobile/templates/mobile/base_1.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MobileService</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <!-- Статическая навигационная панель -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'mobile:index' %}">
              MobileService</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
<!--          <ul class="nav navbar-nav">
            <li><a href="{% url 'mobile:index' %}"> MobileService</a></li>
          </ul>   -->
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
              <li><a href="{% url 'send_email:settings_common' %}">settings</a></li>
              <li><a href="{% url 'users:individual' %}">individual</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
        </div>
      <div class="row">
        <div class="col-xs-12 col-sm-3">
          <ul class="rounded">
            <li><a href="{% url 'users:service_prices' %}"><h3>Service prices</h3></a></li>
            <li><a href="{% url 'mobile:telephones' %}"><h3>Telephones</h3></a></li>
            <li><a href="{% url 'users:details' %}"><h3>Details</h3></a></li>
            <li><a href="{% url 'users:handbook' %}"><h3>Handbook</h3></a></li>
            <li><a href="{% url 'send_email:messages' %}"><h3>Messages</h3></li>
            <li><a href="{% url 'send_email:settings_common' %}"><h3>Settings</h3></a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-9">
          <div>
           {% block content %}{% endblock content %}
          </div>
        </div>
    </div> <!-- /container -->
  </body>
</html>

mobile/templates/mobile/edit_record.html
{% extends "mobile/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Telephones</h2><h4>edit</h4>
{% endblock header %}
{% block content %}
  <form action="{% url 'mobile:edit_record' mobil.id %}" method='post'>
      {% csrf_token %}
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.number_reg %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.number_sticker %}
      </div>
      <div class="col-xs-12 col-sm-3 col-sm-offset-3">
        {% if mobil.number_tel != '+370' or mobil.email_client != '*@gmail.com' %}
          {% if set_1.free_set == 'Yes' %}
            <a href="{% url 'send_email:messages_mobil' mobil.id%}"><h3>Send message</h3></a>
          {% else %}
            <p>Чтобы отправить сообщение - измените</p>
            <a href="{% url 'send_email:settings_common' %}"><h4>Settings</h4></a>
          {% endif %}
        {% else %}
           <h3>Send message</h3>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.model_tel %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.model_1_tel %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.imei %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.kod_tel %}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.defect_tel %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.defect %}
      </div>

      <div class="col-xs-12 col-sm-3 col-sm-offset-3">
        {% bootstrap_field form.price %}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.state %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.status %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.email_client %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.number_tel %}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.date_end %}
      </div>
      <div class="col-xs-12 col-sm-3">
        {% bootstrap_field form.date_take_away %}
      </div>
      <div class="col-xs-12 col-sm-3 col-sm-offset-3">
        {% bootstrap_field form.comment %}
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-3 ">
        <h3></h3>
      </div>
    </div>
   {% buttons %}
       <div class="row">
          <div class="col-sm-offset-10 ">
            <button name="submit" class="btn btn-primary">save</button>
            <a href="{% url 'mobile:telephones' %}" class="btn btn-danger" >
		      cancel</a>
          </div>
       </div>
    {% endbuttons %}
  </form>

{% endblock content %}
  

mobile/templates/mobile/index.html
{% extends "mobile/base.html" %}
{% block header %}
  <div class='jumbotron'>
    <h1>MobileService</h1>
  </div>
{% endblock header %}
{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own database.
  </h2>
{% endblock content %}

mobile/templates/mobile/search_results.html
{% extends "mobile/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Telephones</h2><h4>search</h4>
{% endblock header %}
{% block content %}
  {%if object_list %}
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr class="info">
          <th style="width:8%">Регистр</th>
          <th style="width:4%">Стикер</th>
          <th colspan="2">Модель телефона</th>
          <th style="width:12%">IMEI</th>
          <th style="width:16%">Неисправность</th>
          <th style="width:8%">Статус</th>
          <th style="width:8">Телефон</th>
          <th style="width:9%">Сдан(дата)</th>
          <th style="width:4%"></th>
          <th style="width:5%"></th>
          <th style="width:7%"></th>
        </tr>
      </thead>
      <tbody>
        {% for mobil in object_list %}
        <tr>
          <td>{{mobil.complex_number_reg}}</td>
          <td>{{mobil.number_sticker}}</td>
          {% if mobil.model_tel == "------->" %}
            <td></td>
          {% else %}
            <td>{{mobil.model_tel}}</td>
          {% endif %}
          <td>{{mobil.model_1_tel}}</td>
          <td>{{mobil.imei}}</td>
          {% if mobil.defect == "*" %}
            <td>{{mobil.defect_tel}}</td>
          {% elif mobil.defect == "***" %}
            <td>{{mobil.defect_tel}}</td>
          {% elif mobil.defect_tel == "------->" %}
            <td>{{mobil.defect}}</td>
          {% else %}
            <td>{{mobil.defect_tel}} , {{mobil.defect}}</td>
          {% endif %}
          <td>{{mobil.status}}</td>
          <td>{{mobil.number_tel}}</td>
          <td>{{mobil.date_added|date:'M d, Y '}}</td>
          <td><a href="{% url 'mobile:edit_record' mobil.id %}" class="btn btn-warning">edit</a></td>
          <td><a href="{% url 'mobile:delete_record' mobil.id %}" class="btn btn-danger">delete</a></td>
          <td><a href="{% url 'mobile:telephones' %}" class="btn btn-warning">cancel</a></td>
        </tr>
        {% endfor %}
        {%else%}
          <p><h2>The list is empty</h2></p>
          <div class="row">
            <div class="col-sm-offset-11 ">
              <a href="{% url 'mobile:telephones' %}" class="btn btn-danger" >
                 cancel</a>
            </div>
          </div>
        </tbody>
  {%endif%}
{% endblock content %}

mobile/templates/mobile/telephones.html
{% extends "mobile/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Telephones</h2><h4>{{user.username}}</h4>
{% endblock header %}
{% block content %}
  <div class="row">
    <div class="col-sm-offset-8">
      <form action="{% url 'mobile:search_results' %}" method="get" autocomplete="off" >
        <input name="q" type="text" placeholder="Search...">
        <button type="submit" class="btn btn-success btn-sm">search</button>
        <a href="{% url 'mobile:new_record' %}" class="btn btn-primary btn-sm">add record</a>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <h3></h3>
    </div>
  </div>
  <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr class="info">
        <th style="width:8%">Регистр</th>
        <th style="width:4%">Стикер</th>
        <th colspan="2">Модель телефона</th>
        <th style="width:12%">IMEI</th>
        <th style="width:20%">Неисправность</th>
        <th style="width:8%">Статус</th>
        <th style="width:8%">Телефон</th>
        <th style="width:9%">Сдан(дата)</th>
        <th style="width:4%"></th>
        <th style="width:5%"></th>
      </tr>
    </thead>
    <tbody>
      {% for mobil in mobils %}
        <tr>
          <td>{{mobil.complex_number_reg}}</td>
          <td>{{mobil.number_sticker}}</td>
          {% if mobil.model_tel == "------->" %}
            <td></td>
          {% else %}
            <td>{{mobil.model_tel}}</td>
          {% endif %}
          <td>{{mobil.model_1_tel}}</td>
          <td>{{mobil.imei}}</td>
          {% if mobil.defect == "*" %}
            <td>{{mobil.defect_tel}}</td>
          {% elif mobil.defect == "***" %}
            <td>{{mobil.defect_tel}}</td>
          {% elif mobil.defect_tel == "------->" %}
            <td>{{mobil.defect}}</td>
          {% else %}
            <td>{{mobil.defect_tel}} , {{mobil.defect}}</td>
          {% endif %}
          <td>{{mobil.status}}</td>
          <td>{{mobil.number_tel}}</td>
          <td>{{mobil.date_added|date:'M d, Y '}}</td>
          <td><a href="{% url 'mobile:edit_record' mobil.id %}" class="btn btn-warning btn-xs">edit</a></td>
          <td><a href="{% url 'mobile:delete_record' mobil.id %}" class="btn btn-danger btn-xs">delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}